package com.example.kanjiread
import kotlin.random.Random

class KanjiGeneratorGradeOne{
    data class Kanji(val character: String, val kunReading: String, val onReading: String)

    // Array di oggetti Kanji rappresentanti i primi 10 kanji di Grado 1
    private val kanjiList = arrayOf(
        Kanji("一", "ひとつ", "イチ"),
        Kanji("右", "みぎ", "ウ"),
        Kanji("雨", "あめ", "ウ"),
        Kanji("円", "えん", "エン"),
        Kanji("王", "おう", "オウ"),
        Kanji("音", "おと", "オン"),
        Kanji("下", "した", "カ"),
        Kanji("火", "ひ", "カ"),
        Kanji("花", "はな", "カ"),
        Kanji("貝", "かい", "カイ"),
        Kanji("学", "がく", "ガク"),
        Kanji("気", "き", "キ"),
        Kanji("九", "きゅう", "キュウ"),
        Kanji("休", "やすむ", "キュウ"),
        Kanji("玉", "たま", "ギョク"),
        Kanji("金", "かね", "キン"),
        Kanji("空", "そら", "クウ"),
        Kanji("月", "つき", "ゲツ"),
        Kanji("犬", "いぬ", "ケン"),
        Kanji("見", "みる", "ケン"),
        Kanji("五", "ご", "ゴ"),
        Kanji("口", "くち", "コウ"),
        Kanji("校", "こう", "コウ"),
        Kanji("左", "ひだり", "サ"),
        Kanji("三", "さん", "サン"),
        Kanji("山", "やま", "サン"),
        Kanji("子", "こ", "シ"),
        Kanji("四", "し", "シ"),
        Kanji("糸", "いと", "シ"),
        Kanji("字", "じ", "ジ"),
        Kanji("耳", "みみ", "ジ"),
        Kanji("七", "なな", "シチ"),
        Kanji("車", "くるま", "シャ"),
        Kanji("手", "て", "シュ"),
        Kanji("十", "とお", "ジュウ"),
        Kanji("出", "でる", "シュツ"),
        Kanji("女", "おんな", "ジョ"),
        Kanji("小", "ちいさい", "ショウ"),
        Kanji("上", "うえ", "ジョウ"),
        Kanji("森", "もり", "シン"),
        Kanji("人", "ひと", "ジン"),
        Kanji("水", "みず", "スイ"),
        Kanji("正", "ただしい", "セイ"),
        Kanji("生", "いきる", "セイ"),
        Kanji("青", "あお", "セイ"),
        Kanji("夕", "ゆう", "セキ"),
        Kanji("石", "いし", "セキ"),
        Kanji("赤", "あか", "セキ"),
        Kanji("千", "せん", "セン"),
        Kanji("川", "かわ", "セン"),
        Kanji("先", "さき", "セン"),
        Kanji("早", "はやい", "ソウ"),
        Kanji("草", "くさ", "ソウ"),
        Kanji("足", "あし", "ソク"),
        Kanji("村", "むら", "ソン"),
        Kanji("大", "おおきい", "ダイ"),
        Kanji("男", "おとこ", "ダン"),
        Kanji("竹", "たけ", "チク"),
        Kanji("中", "なか", "チュウ"),
        Kanji("虫", "むし", "チュウ"),
        Kanji("町", "まち", "チョウ"),
        Kanji("天", "てん", "テン"),
        Kanji("田", "た", "デン"),
        Kanji("土", "つち", "ド"),
        Kanji("二", "ふた", "ニ"),
        Kanji("日", "ひ", "ニチ"),
        Kanji("入", "はいる", "ニュウ"),
        Kanji("年", "ねん", "ネン"),
        Kanji("白", "しろ", "ハク"),
        Kanji("八", "やっつ", "ハチ"),
        Kanji("百", "ひゃく", "ヒャク"),
        Kanji("文", "ふみ", "ブン"),
        Kanji("木", "き", "モク"),
        Kanji("本", "ほん", "ホン"),
        Kanji("名", "な", "メイメイ"),
        Kanji("目", "め", "モク"),
        Kanji("立", "たつ", "リツ"),
        Kanji("力", "ちから", "リョク"),
        Kanji("林", "はやし", "リン"),
        Kanji("六", "むっつ", "ロク"),
)

    // Metodo per generare casualmente un kanji e ottenere le sue letture Kun e On
    fun generateRandomKanji(): Kanji {
        val randomIndex = Random.nextInt(kanjiList.size)
        return kanjiList[randomIndex]
    }
}